# Main config file

appname:    "Harbour"
charset:    "UTF-8"
serializer: "JSON"

engines:
  JSON:
    allow_blessed: 1
    convert_blessed: 1

plugins:
    Database:
        driver:         "mysql"
        database:       "harbour"
        host:           "127.0.0.1"
        port:           3306
        username:       "root"
        password:       ""
        log_queries:    1
        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'"]
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
            InactiveDestroy: 1

session_name: "harbour.session"
session: "DBI"
session_options:
    dsn:      "DBI:mysql:database=harbour;host=127.0.0.1;port=3306"
    table:    "session"
    user:     "root"
    password: ""
